Langs['en'] = {
    -- * Elevator
    ['general.elevator'] = '~r~[E]~s~ Elevator',
    ['general.elevator_header'] = 'Elevator',
    ['general.elevator_description'] = 'Maybe you can go anywhere.',
    ['general.elevator_teleported_msg'] = 'You came to the %s floor',
    ['general.floor'] = 'Floor - %s',

    -- * Auto Changer
    ['auto.sql_type_changed'] = 'Sql Type Changed to %s',
    ['auto.inventory_changed'] = 'Inventory Type Changed to %s',
    ['auto.metasystem_changed'] = 'Meta System Changed to %s',
    ['auto.framework_changed'] = 'Framework Changed to %s',

    -- * Room Sharing
    ['sharing.does_not_have_room'] = 'You don\'t have a room. so you cant use this command',
    ['sharing.maximum'] = 'You can\'t share your key with more friends!',
    ['sharing.target_not_have_key'] = 'Target doesn\'t have the key',
    ['sharing.you_unshared_key'] = 'Someone took your key back from you.',
    ['sharing.key_unshared'] = 'You got your key back.',
    ['sharing.you_shared_key'] = 'You now have the key to the %s',
    ['sharing.key_shared'] = 'You shared your key.',
    ['general.not_useable'] = 'Do a crazy and give your motelkey.',
    ['general.share_key'] = 'Share Key',
    ['general.share_key_desc'] = 'Closest Players',
    ['general.share_key_modal'] = 'Are you sure you want to share your key?',
    ['general.un_share_key'] = 'Unshare Your Key',
    ['general.un_share_key_desc'] = 'Select the player you want to unshare your key',
    ['general.un_share_key_modal'] = 'Are you sure you want to get the key back?',
    ['general.room_sharing'] = 'Room Sharing',
    ['general.room_sharing_desc'] = 'You can share your key with the friends',

    -- * Creator
    ['creator.title'] = 'Creator Menu',
    ['creator.sale'] = 'Motel sale percentage',
    ['creator.sale.tooltip'] = 'How much times of the sale price. Example: 1.5 = 150% of the sale price.',
    ['creator.room_count'] = 'Room Count',
    ['creator.warning.expense.title'] = 'Warning Expenses',
    ['creator.warning.first'] = 'First Warning',
    ['creator.warning.second'] = 'Second Warning',
    ['creator.warning.third'] = 'Third Warning',
    ['creator.warning.last'] = 'Last Warning',
    ['creator.warning_expense.tooltip'] = 'If the rent is not paid, how much will the rent price increase?',
    ['creator.motel_type'] = 'Motel Type',
    ['creator.popup'] = 'Do you want to create a motel?',
    ['creator.error.name.exists'] = 'Motel with this name already exists',
    ['creator.deleted_room'] = 'You deleted the room. Room: %s',
    ['creator.text.door'] = 'Room - %s',
    ['creator.text.stash'] = 'Room - %s Stash',
    ['creator.text.gardrobe'] = 'Room - %s Gardrobe',
    ['creator.select.door'] = 'You must to select a door!',
    ['creator.complete.room'] = 'You must add at least one room! And don\'t forget to add a gardrobe and stash!',
    ['creator.point.near'] = 'This point is too close to other point!',
    ['creator.add.door'] = 'Add Door',
    ['creator.add.stash'] = 'Add Stash',
    ['creator.add.gardrobe'] = 'Add Gardrobe',
    ['creator.select.reception'] = 'Select reception point',
    ['creator.select.room.management'] = 'Set Room Management Point',
    ['creator.select.shell.point'] = 'Set Shell Point',
    ['creator.select.exit.point'] = 'Set Exit Point',
    ['creator.select.entry.point'] = 'Set Entry Point',
    ['creator.select.room_management'] = 'Awesome, now select the room management point',
    ['creator.select.rooms'] = 'Last step, create rooms',
    ['creator.point.busy'] = 'This point is selected. Select another point',
    ['creator.inside.text.stash'] = 'Stash - %s',
    ['creator.inside.text.gardrobe'] = 'Gardrobe - %s',
    ['creator.inside.complete'] = 'You must add at least one stash and gardrobe!',
    ['creator.door.create'] = 'You must add at least one door',
    ['creator.select.ipl'] = 'Select a ipl',
    ['creator.select.shell'] = 'Select a shell',
    ['creator.select.exit'] = 'Select exit position',
    ['creator.select.inside'] = 'Select stash and gardrobe points',
    ['creator.select.entry'] = 'Select room entry point',
    ['creator.inside.point.outside'] = 'Point is outside of shell',
    ['creator.forward'] = 'Forward +/-',
    ['creator.right'] = 'Right +/-',
    ['creator.increase_speed'] = 'Increase Speed',
    ['creator.next_state'] = 'Change State',
    ['creator.up'] = 'Up +/-',
    ['creator.add_point'] = 'Add Point',
    ['creator.set_any'] = 'Set',
    ['creator.undo_point'] = 'Undo Last',
    ['creator.set_position'] = 'Set Position',
    ['creator.rotate_z'] = 'RotateZ +/-',
    ['creator.rotate_z_scroll'] = 'RotateZ +/-',
    ['creator.increase_z'] = 'Z Boundary +/-',
    ['creator.decrease_z'] = 'Z Boundary +/-',
    ['creator.change_shell'] = 'Change Shell +/-',
    ['creator.cancel'] = 'Cancel',
    ['creator.leftApt'] = 'Previous Apartment',
    ['creator.rightApt'] = 'Next Apartment',
    ['creator.hide_texts'] = 'Toggle Texts',
    ['creator.coords_not_in_shell'] = 'Coords is not in shell',

    -- * Creator Blips
    ['creator.blip.sprite'] = 'Sprite',
    ['creator.blip.sprite.help'] = 'Blip\'s sprite',
    ['creator.blip.color'] = 'Color',
    ['creator.blip.color.help'] = 'Blip\'s color',
    ['creator.blip.scale'] = 'Scale',
    ['creator.blip.scale.help'] = 'Blip\'s scale',
    ['creator.blip.name'] = 'Name',
    ['creator.blip.name.help'] = 'Blip\'s name',

    -- * Creator Checkboxes
    ['creator.checkbox.sell'] = 'Motel is salable',
    ['creator.checkbox.purchasable'] = 'Purchasable',
    ['creator.checkbox.auto'] = 'Auto System',
    ['creator.checkbox.blip'] = 'Blip',

    -- * Creator Inputs
    ['creator.input.name'] = 'Motel Name',
    ['creator.input.name.help'] = 'Motel\'s awesome name',
    ['creator.input.cost'] = 'Cost',
    ['creator.input.cost.help'] = 'Room cost per minute',
    ['creator.input.key_cost'] = 'Key Cost',
    ['creator.input.key_cost.help'] = 'Cost of a new key',
    ['creator.input.sale'] = 'Sale Price',
    ['creator.input.sale.help'] = 'Motel\'s sale price',


    -- * Inventory
    ['general.item_putted'] = 'Item putted to room. Item: %s amount: %s',
    ['general.item_taken'] = 'Item taked to room. Item: %s amount: %s',
    ['general.cant_get_item'] = 'You cannot get this item!',
    ['general.stash_does_not_have_item'] = 'This item is not in stash?',
    ['general.stash_cant_take_item'] = 'Stash can\'t get any more items!',
    ['general.not_enough_item'] = 'You don\'t own this item!',
    ['general.take_item'] = 'Take Item: %s',
    ['general.your_inventory'] = 'Your Inventory',
    ['general.your_inventory_description'] = 'So you see your items. What do you want to do?',
    ['general.stash'] = 'Motel Inventory',
    ['general.stash_description'] = 'You see the room\'s items. Maybe these are not yours?',
    ['general.store_item'] = 'Store Item: %s',
    ['general.inventory_header'] = 'Room Stash',
    ['general.inventory_description'] = 'Don\'t forget to get your items back kiddo.',
    ['general.inventory_warn'] = 'Stash is being viewed by someone else...',

    -- * General
    ['general.sended_message'] = 'Message sent',
    ['general.no_players_nearby'] = 'No players nearby.',
    ['general.no_shared_player'] = 'You didn\'t share your room with anyone!',
    ['general.cant_leave_room'] = 'You can\'t leave your room without paying your rent!.',
    ['general.rent_room_text'] = '[~r~E~s~] to rent a room',
    ['general.salary'] = 'Salary',
    ['general.confirm'] = 'Confirm',
    ['general.refuse'] = 'Refuse',
    ['general.cancel'] = 'Cancel',
    ['general.time'] = 'Time',
    ['general.price'] = 'Price',
    ['general.count'] = 'Count',
    ['general.payment'] = 'Payment - ',
    ['general.day'] = 'Day',
    ['general.hour'] = 'Hour',
    ['general.minute'] = 'Minute',
    ['general.reception_successfullyquit'] = 'You succesfully quit your job',
    ['general.welcome'] = 'Hi, Welcome Back',
    ['general.utc'] = 'UTC',
    ['general.quit_job_modal'] = 'Are you sure you want to quit your job?',
    ['general.sell_motel_modal'] = 'Are you sure you want to sell the motel for ',
    ['general.are_you_sure'] = 'Are You Sure?',
    ['general.modal_confirm'] = 'Yes, I\'m sure',
    ['general.modal_cancel'] = 'No, cancel',
    ['general.message'] = 'Message',
    ['general.access_denied'] = 'You do not have permission to do this action',
    ['general.not_enough_money'] = 'You don\'t have enough money.',
    ['general.not_enough_money_count'] = 'You don\'t have enough money. Required $%s',
    ['general.have_already_room'] = 'This person have already a motel room.',
    ['general.room_have_owner'] = 'This room have already a owner',
    ['general.teleported_msg'] = 'You teleported the front of the door',
    ['general.not_closest_room'] = 'You are not near the room',
    ['general.nearby_motel'] = 'There is another motel nearby.',
    ['general.not_exists_shell'] = 'You don\'t have a shell. Please add it to the Config.Shells',

    -- * Raid
    ['raid.not_job'] = 'You can\'t use this',
    ['raid.success'] = 'You broked',

    -- * Admin Modal
    ['admin.select_motel'] = 'Select Motel',
    ['admin.select_player'] = 'Select Player',
    ['admin.show_all_motels'] = 'Show also owned motels.',
    ['admin.modal'] = 'Are you sure want to give the motel?',

    -- * Validations
    ['validation.number'] = 'Value must be a number',
    ['validation.required'] = 'This field is required',
    ['validation.min'] = 'Value must be greater than ',
    ['validation.max'] = 'Value must be less than ',

    -- * Reception Menu
    ['general.reception'] = '~r~[E]~s~ Reception',
    ['general.dashboard'] = 'Dashboard',
    ['general.employees'] = 'Employees',
    ['general.customers'] = 'Customers',
    ['general.nearby'] = 'Nearby Players',
    ['general.storage'] = 'Motel Storage',
    ['general.requests'] = 'Customer Requests',
    ['general.sell_motel'] = 'Sell ​​Motel',
    ['general.my_room'] = 'My Room',
    ['general.rent_room'] = 'Rooms',

    -- * Dashboard
    ['dashboard.employee_header'] = 'Employees',
    ['dashboard.empty_rooms'] = 'Empty Rooms',
    ['dashboard.customers'] = 'Customers',
    ['dashboard.transactions'] = 'Last Transactions',

    -- * Rooms
    ['room.header'] = 'Room',
    ['room.desc'] = 'Room - ',
    ['room.change_modal'] = 'Are you sure you want to change the room?',

    -- * Employees
    ['employees.employee'] = 'Employee',
    ['employees.fire'] = 'Fire',
    ['employees.fire_person'] = 'Fire the person',
    ['employees.fire_modal'] = 'Are you sure you want to fire this person?',
    ['employees.message'] = 'Message',
    ['employees.send_message'] = 'Send Message',
    ['employees.prize'] = 'Prize',
    ['employees.give_prize'] = 'Give the prize',
    ['employees.prize_modal'] = 'Are you sure you want to give the prize?',
    ['employees.salary'] = 'Update Salary',
    ['employees.update_salary'] = 'Update Salary',
    ['employees.salary_modal'] = 'Are you sure you want to update the salary?',
    ['employees.kick'] = 'Out Of The Room',
    ['employees.change'] = 'Change Room',
    ['employees.refresh'] = 'Refresh time',
    ['employees.create_key'] = 'Create a new key',
    ['employees.send_message_perm'] = 'Send Message',
    ['employees.rent'] = 'Motel Room Rental',
    ['employees.show_requests'] = 'View Requests',
    ['employees.withdraw'] = 'Withdraw Money',
    ['employees.deposit'] = 'Deposit Money',
    ['employees.update_status'] = 'Update Motel Status',
    ['employees.open_room'] = 'Access To Rooms',

    -- * Customers
    ['customers.debt'] = 'Debt: ',
    ['customers.update_status'] = 'Update Room Status',
    ['customers.update_status_modal'] = 'Are you sure you want to update the room status?',
    ['customers.kick'] = 'Kick',
    ['customers.kick_desc'] = 'Kick The Person Out Of The Room',
    ['customers.kick_modal'] = 'If you do this. The person does not pay the rent for the motel room.',
    ['customers.change_room'] = 'Change Room',
    ['customers.rem_time'] = 'Remaining Time',
    ['customers.create_key'] = 'Create Key',
    ['customers.create_key_desc'] = 'Create a new key',
    ['customers.create_key_modal'] = 'Are you sure you want to create a new key?',
    ['customers.send_message'] = 'Send Message',
    ['customers.send_message_modal'] = 'Are you sure you want to send a message?',
    ['customers.message'] = 'Message',
    ['customers.have_unpaid_bill'] = 'You can\'t rent a room because you have an unpaid bill!',

    -- * Nearby Players
    ['nearby.header'] = 'Nearby Player',
    ['nearby.recruit'] = 'Recruit',
    ['nearby.recruit_desc'] = 'Recruit The Person',
    ['nearby.modal_sure_recruit'] = 'Are you sure want recruit this player?',
    ['nearby.rent_room'] = 'Rent Room',
    ['nearby.rent_room_desc'] = 'Rent A Room For The Person',
    ['nearby.dropdown_employee_perms_header'] = 'Employee Permissions',
    ['nearby.has_bill'] = 'The person has an unpaid bill. Still sure you want to rent the room?',
    ['nearby.modal_rent_room'] = 'Are you sure you want to rent the room to the player?',
    ['nearby.target_has_bill'] = 'You can\'t rent a room to the person because they have an unpaid bill!',

    -- * Storage
    ['storage.current'] = 'Current Money',
    ['storage.quantity'] = 'Enter Quantity',
    ['storage.not_data'] = 'No data found for the motel',
    ['storage.deposit'] = 'Deposit Money',
    ['storage.deposit_modal'] = 'Are you sure you want to deposit ',
    ['storage.withdraw'] = 'Withdraw Money',
    ['storage.withdraw_modal'] = 'Are you sure you want to withdraw',
    ['storage.not_enough_money_for_employee'] = 'You didn\'t get your salary because there is not enough money in the storage.',
    ['storage.notEnoughtMoney'] = 'Not enough money on storage',
    ['storage.not_enough_deposit'] = 'Not enough money in the storage to deposit',
    ['storage.success_withdraw'] = 'Money was taken. Amount withdrawn: %s',
    ['storage.success_deposit'] = 'The money has been deposited. Your deposit amount: %s',

    -- * Customer Requests
    ['requests.header'] = 'Customer Request',
    ['requests.request'] = 'Request',
    ['requests.employee'] = 'Employee',
    ['requests.modal'] = 'Are you sure you want to accept the request?',
    ['requests.modal_confirm'] = 'Confirm, Request',
    ['requests.modal_cancel'] = 'Cancel, Request',
    ['requests.new_key'] = 'New Key',
    ['requests.room_change'] = 'Room Change',

    -- * Self Room
    ['self.rent'] = 'Rent Debt ',
    ['self.pay_rent'] = 'Pay Your Rent',
    ['self.pay_amount'] = 'Amount',
    ['self.leave_header'] = 'Leave The Motel',
    ['self.leave'] = 'Leave Motel',
    ['self.leave_modal'] = 'Are you sure you want to leave the room?',
    ['self.create_key'] = 'Create Key',
    ['self.create_key_desc'] = 'Create a new key',
    ['self.create_key_modal'] = 'Are you sure you want to create a new key?',

    ['self.valid'] = 'Please enter a valid amount',
    ['self.rent_less_debt'] = 'You cant pay more than your debt!',
    ['self.rent_modal'] = 'Are you sure you want to pay the rent?',
    ['self.req_man'] = 'Request Management',
    ['self.call_employee'] = 'Call Employee',
    ['self.req_key'] = 'Request Key',
    ['self.room_change'] = 'Request Room Change',
    ['self.max_time'] = 'You can not increase your rent time more than 30 days',
    ['self.error'] = 'Unexpected error',
    ['self.increase_time_success'] = 'Time increased successfully',
    ['self.increase_time_popup_header'] = 'Are you sure you want to increase time?',
    ['self.increase_time_header'] = 'Increase Time',
    ['self.increase_time'] = 'Increase Time',

    -- * Self Rent
    ['self.modal_rent_room'] = 'Are you sure you want to rent the room?',

    ['general.reception_notplayerfound'] = 'Player not found!',
    ['general.reception_notplayerdata'] = 'Player data not found ?',
    ['changed_room'] = 'Motel room changed, new room - %s',
    ['general.reception_deletedMotelRoom'] = '%s\'s motel room was deleted',
    ['general.reception_changedMotel'] = 'The motel room was changed.',
    ['general.reception_succesfullytakeemploye'] = 'You hired the person.',
    ['general.reception_succesfullytakeemployeTarget'] = 'You are now an employee at the %s. Your salary: %s',
    ['general.reception_open'] = 'Open',
    ['general.reception_close'] = 'Close',
    ['general.reception_accessdenied'] = 'insufficient Permissions',
    ['general.reception_createdRoomKey'] = 'You Created New Key.',
    ['general.reception_successfullykicked'] = 'Person successfully fired',
    ['general.reception_rewardSenderMsg'] = 'You successfully awarded $ %s',
    ['general.reception_rewardTakerMsg'] = 'You received an award from the owner of the motel. Amount you received %s',
    ['general.reception_updateSalarySenderMsg'] = 'You successfully set the person\'s salary $ %s',
    ['general.reception_updateSalaryTakerMsg'] = 'Your salary has been updated. Your new salary: %s',
    ['general.reception_ownedRoom'] = 'Someone else rented this motel room.',
    ['general.reception_notPay'] = 'You have no rent to pay.',
    ['general.reception_notReqPay'] = 'The amount you want to pay is more than your rent.',
    ['general.reception_payed'] = 'Paid the rent.',
    ['general.reception_leftedRoom'] = 'You Left The Motel Room.',
    ['general.reception_buyMotel'] = '~r~[E]~s~ Buy Motel',
    ['general.reception_requestgetEmployee'] = 'Call employee',
    ['general.reception_requestKey'] = 'Request Key',
    ['general.reception_requestMain'] = 'Request Management',
    ['general.reception_requestChangeRoom'] = 'Request room change',
    ['general.reception_requestExtendTime'] = 'Request extension',
    ['general.suspended'] = 'Suspended',
    ['general.active'] = 'Active',
    ['general.reception_updatedSuspended'] = 'Your motel room has been suspended by the motel management',
    ['general.reception_updatedBeat'] = 'Your motel room has been restored by the motel management',
    ['general.reception_urNotRoom'] = 'You don\'t have a motel room.',
    ['general.reception_kickAreyouSure'] = 'Do you want to throw this person out?',
    ['general.reception_Employeekicked'] = 'You got fired by the boss.',
    ['reception.customer_kicked'] = 'Your motel room was deleted by the worker. But don\'t worry. You don\'t have to pay your rent.',
    ['general.reception_notIngame'] = 'The person is not in the game.',
    ['general.static.motel'] = 'This motel is static. You can\'t delete it. You can only delete motels created in-game',
    ['general.no_nearby_motel'] = 'You are not close to any motels. Make sure you\'re close to the reception',
    ['general.open.room_menu'] = '~r~[E]~s~ Open Room Menu',
    ['general.not_exist_available_room'] = 'There are no rooms in the motel that you can enter.',
    ['general.room.menu'] = 'Room Menu',
    ['general.room.menu.description'] = 'You can go to your room or u.u',
    ['general.room'] = 'Room',
    ['general.owner'] = '(Yours)',
    ['general.unlocked'] = '🔓 Unlocked',
    ['general.locked'] = '🔒 Locked',

    -- * Transactions
    ['trans.deposite'] = '%s deposited %s',
    ['trans.withdraw'] = '%s withdrawed %s',
    ['trans.leave_room'] = '%s Leaved the room',
    ['trans.take_employee'] = '%s is the new employee!',
    ['trans.rent_room'] = '%s Rented %s st room',
    ['trans.pay_rent'] = '%s paid the rent. Last rent: %s',

    -- * Stash
    ['stash'] = '~r~[E]~s~ Stash',

    -- * Gardrobe
    ['gardrobe'] = '~r~[E]~s~ Gardrobe',
    ['gardrobe_changeoutfit'] = 'Change Outfit',
    ['gardrobe_deleteoutfit'] = 'Delete Outfit',
    ['gardrobe_saveoutfit'] = 'Save Outfit',
    ['gardrobe_cabinet'] = 'Gardrobe',
    ['wardrobe_selectName'] = 'Set Outfit Name',

    --* Bill
    ['general.bill'] = '~r~[E]~s~ Bill Menu',
    ['general.not_bill'] = 'There are no bills..',
    ['general.bill_paid'] = 'You Paid Your Bill. Amount you pay %s',
    ['general.are_you_sure_pay'] = 'Are you sure you want to pay your bill?',
    ['general.bill_pay'] = '~g~Pay~s~',
    ['general.bill_cancel'] = '~r~Cancel~s~',
    ['general.bills_header'] = 'Bills',
    ['general.bills_description'] = 'It\'s important to pay your bills.',
    ['general.bill_name'] = 'You got a $%s bill from the %s.',
    ['general.bill_create'] = 'A bill of %s has been issued in such an amount.',

    -- * Employee
    ['employee_autosystemactive'] = 'Automatic wage payment of employees\'s active',
    ['employee_notauthautotime'] = 'The time for automatic wage payment of workers has been entered incorrectly!!',
    ['employee_AutoPay'] = 'You got paid at the motel! $%s',

    -- * Admin Command
    ['setmotelowner.not_admin'] = 'This command only useable by admin',

    -- * Print
    ['SaveRent'] = '%s rent has been saved. Time: %s',
    ['general.items_saved'] = '%s stash is saved',
    ['UpdatedPlayer'] = '%s data has been saved.',
    ['autosave_active'] = 'Autosave is on',
    ['playerdropped_SaveRent'] = ' Player Dropped, saved data, next lease time %s',
    ['general.dropped_framework_error'] = 'Player Dropped but data\'s not found',
    ['playerdropped_UpdatedPlayer'] = ' %s data\'s saved',
    ['allplayer_saved'] = 'Motel\'s Data Saved. on ^4%s^0 seconds',
    ['notsupporteddatabase'] = 'database is not supported. Make the settings via config.',
    ['database_connection'] = 'Database connection is being established.',
    ['database_connected'] = 'Established with database over ^4%s^0 seconds',
    ['general.items_fetched'] = 'Esx inventory data has been fetched',
    ['wrong_autosave'] = 'Only numbers can be entered in the Config.autoSaveTime section.',
    ['employee_active'] = 'Worker System Active',
    ['employee_notsalaryMethod'] = 'Employee salary method is wrong!',

    ['permission_active'] = 'Active',
    ['permission_deactive'] = 'Passive',

    ['general.room_menu.admin'] = '(Admin Permission)',

    -- * Log
    ['general.rent_motel'] = '**%s Rented A Room** \n **Motel Name**: %s \n **Room ID**: %s \n **Time**: %s \n **Price**: $%s',
    ['general.motel_owner'] = 'Motel Owner',
    ['general.rented_by'] = 'Rented By',
    ['general.admin'] = 'Admin',
    ['general.player'] = 'Player',
    ['general.employee'] = 'Worker',
    ['general.license'] = 'LICENSE',
    ['general.steam'] = 'STEAM ID',
    ['general.buy'] = 'ROOM RENT',
    ['log_stash'] = 'STASH',
    ['log_stored_item'] = '%s Put Things In The %s \n **Room ID**: %s \n **Item Name**: %s \n **Amount**: %s',
    ['log_taked_item'] = '%s Taked Something from the %s \n **Room ID**: %s \n **Item Name**: %s \n **Amount**: %s',
    ['log_resetrent'] = '**%s** leaved the room \n Motel Name **%s** \n Rent Status **%s**',
    ['log_payed'] = 'Paided',
    ['log_notpayed'] = 'Not paided',
    ['log_resrent'] = 'Leave Room',
    ['log_setmotelowner'] = '**Changed owner of the %s** \n **Admin**: %s \n **New Owner**: %s',
    ['log_setmotel'] = 'REPLACE MOTEL OWNER',
    ['log_deposite'] = 'Deposit',
    ['log_deposite_money'] = '**%s** deposited **$%s** in the **%s**',
    ['log_withdrawMoney'] = '**%s** withdrawed **$%s** in the **%s**',
    ['log_withdraw'] = 'Withdraw',
    ['log_changeRoom'] = '**%s** changed the room. \n **Customer**: %s \n **Motel Name**: %s \n **Old Room ID**: %s \n **New Room ID**: %s',
    ['log_chh'] = 'Change Room',
    ['log_autodeletemotel'] = '**%s**\'s room deleted. \n Motel Name: **%s** \n Motel Room ID: **%s**',
    ['log_autodelete'] = 'RENT CANCEL',
    ['log_deletemotelfromplayer'] = '**%s** \'s motel room was deleted. \n Delete manager **%s** \n Motel Name: **%s** \n Motel Room: **%s**',
    ['log_deletemotelfrom'] = 'ROOM RENT CANCEL',
    ['log_takeemployee'] = '**%s** Taked a worker. \n **Player Name**: %s \n **Salary**: $%s',
    ['log_takeemployee_header'] = 'TAKE MOTEL WORKER',
    ['log_updatePermission'] = '**%s** Setted The Permission. \n **Worker**: %s \n **Permission Name**: %s \n **Permission status**: %s',
    ['log_updatePerm'] = 'SET PERMISSION',
    ['log_createNewKey'] = 'The following person **%s** created a new key. \n Motel name: **%s** \n Room ID: **%s** \n Worker **%s**',
    ['log_self_create_key'] = '**%s** created a new key. \n Motel Name: **%s** \n Room ID: **%s**',
    ['log_createdNewKey'] = 'Create a new key',
    ['log_kickEmployee'] = 'That person **%s**\n fired **%s** \n working at that motel. The person he fired **%s**',
    ['log_kickedEmployee'] = 'FIRE THE WORKER',
    ['log_rewardEmployee'] = '**%s** gave bonus. \n **Bonus**: %s \n **Worker**: %s',
    ['log_reward'] = 'Bonus',
    ['log_updateSalary'] = '**%s**\'s salary is updated. \n **Motel Owner**: %s \n **Old Salary**: $%s \n **New Salary**: $%s',
    ['log_updateSal'] = 'Salary Update',
    ['log_leftMotel'] = '**%s Leaved The Room** \n **Motel Name**: %s \n **Room ID**: %s',
    ['log_leftMotelR'] = 'Leave The Room',
    ['log_payRoom'] = '**%s Paid The Rent** \n **Motel**: %s \n **Motel Room**: %s \n **Rent Paid** %s \n **Remaining** %s',
    ['log_payRoomX'] = 'Rent Payment',
    ['log_acceptRequest'] = 'That person **%s** \n accepted the request of **%s** \n from **%s** \n.',
    ['log_acceptRequestX'] = 'Accepting a Request',
    ['log_rejectRequest'] = '**%s** denied \n **%s** \'s request for a \n **%s**',
    ['log_rejectRequestX'] = 'Reject a Request',
    ['log_bill'] = '**%s** paid the bill. \n **Motel Name**: **%s** \n **Bill**: %s',
    ['log_billX'] = 'Pay Bill',
    ['log_createBill'] = '**%s** \n taked a bill. \n **Motel Name**: %s \n **Price**: %s',
    ['log_createBillX'] = 'Create Bill',

    -- * Main
    ['buy_alreadyhouse'] = 'The person already has a motel room',
    ['general.rented_room_send_message_to_worker'] = 'You successfully rented room %s in the %s to %s.',
    ['general.rented_room'] = 'You rented the room price',
    ['general.rented_room_by_worker'] = 'You bought room number %s in the %s from %s!',
    ['notfoundedplayer'] = 'Player not found!',
    ['hacker_probably'] = 'Suspect Cheating! Player ID: %s HEX ID: %s Reason: Tried to rent a motel room',
    ['not_foundedid'] = 'Player ID not found!',
    ['not_reason'] = 'You didnt write reason!',
    ['not_metadata_text'] = '~r~[G]~s~ %s',
    ['not_metadata_locked'] = 'Locked',
    ['not_metadata_unlocked'] = 'Unlocked',
    ['metadata_notnumb'] = 'The key won\'t open this motel room',
    ['metadata_notclosestmotel'] = 'You cannot use the key here.',
    ['second'] = 'Second',
    ['minute'] = 'Minute',
    ['hour'] = 'Hours',
    ['day'] = 'Day',
    ['motel_removed'] = 'Your Motel room was deleted.',
    ['motel_notfounded'] = 'Motel room not found!',
    ['motel_admin'] = 'Management',
    ['general.room.suspended'] = 'This room is suspended.',
    ['general.motel_suspended'] = 'Your motel room was suspended because you didnt pay your motel rent. Pay as soon as you can!',
    ['general.room_is_empty'] = 'This room doesn\'t have a owner. So you can\'t get in',
    ['motel_paySuspended'] = 'Your room price has been taxed from the motel. Pay your rent as soon as possible. New Room Price: %s',
    ['motel_acceptRequest'] = 'Request granted.',
    ['motel_rejectRequest'] = 'Request Denied.',
    ['motel_finalTime'] = 'Your motel room was wiped out because your Motel time was up.',
    ['motel_firstTime'] = 'It\'s halfway to the rent cycle ! Remaining Time %s',
    ['motel_secondTime'] = 'Your rent cycle is getting shorter ! Remaining Time %s',
    ['motel_thirdTime'] = 'Your Motel time is getting shorter ! Remaining Time %s',
    ['motel_successfullyChangedStatus'] = 'The Status Of The Person\'s Motel Room Was Successfully Changed.',
    ['not_motelowner'] = 'You don\'t own a Motel.',
    ['motel_deletedPlayerMsg'] = 'Your motel room was deleted because the Motel owner sold the motel.',
    ['motel_deletedEmployeeMsg'] = 'Because the Motel owner sold the motel, you\'re no longer someone who works in this motel.',
    ['motel_successfullySell'] = 'The Motel Was Sold. Amount you get %s',
    ['motel_requestDesc'] = '%s wants to rent you the %s st motel room for $%s for %s',
    ['motel_requestAccept'] = 'The person accepted your offer.',
    ['motel_requestReject'] = 'The person did not accept your offer.',
    ['motel_requestWaiting'] = 'Waiting for a response from the person, please wait.',
    ['motel_already_sended_request'] = 'You have already sent a offer to the person. Please wait.',
    ['motel.not_exists.room.unique.id'] = 'You must to create a new key for this room',

    ['motel_employeeReqDesc'] = '%s is offering you %s to work at a motel called $%s.',
    ['motel.you_are_owned_now'] = 'The motel %s belongs to you now.',
    ['general.room_management'] = '~r~[E]~s~ Room Management',

    ['open'] = 'Open %s',
    ['interact'] = 'Interact with %s',
    ['door'] = 'Door',
    ['urnotOwnThisRoom'] = 'You don\'t have the key to the room',
    ['alreadyOwnerMotel'] = 'This motel is already owned by another',
    ['enter_room'] = '~r~[E]~s~ Enter Room',
    ['leave_room'] = '~r~[E]~s~ Leave Room',
    ['general.motel_deleted_teleport'] = 'We teleported you because the motel was deleted.',
    ['general.teleported_to_reception'] = 'We teleported you to the reception because your room is gone',

    ['commands.admin.suggestion'] = 'Open Admin Menu (Admin only)',
    ['commands.creator.suggestion'] = 'Open Creator Menu (Admin only)',
    ['commands.creator.delete.suggestion'] = 'Delete the closest motel (Admin only)',
    ['commands.roomsharing.suggestion'] = 'Open Room Sharing Menu'
}
